<a href="https://colab.research.google.com/github/NastasiaMazur/LDA_NPRdataset/blob/main/Latent_Dirichlet_Allocation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Latent Dirichlet Allocation

## Data
articles from NPR (National Public Radio), obtained from their website [www.npr.org](http://www.npr.org)

In [64]:
import pandas as pd

In [2]:
npr = pd.read_csv('npr.csv')

In [3]:
npr.head()

Article
0  In the Washington of 2016, even when the polic...
1    Donald Trump has used Twitter  —   his prefe...
2    Donald Trump is unabashedly praising Russian...
3  Updated at 2:50 p. m. ET, Russian President Vl...
4  From photography, illustration and video, to d...

In [6]:
len(npr)

11992

In [7]:
npr['Article'][0]


'In the Washington of 2016, even when the policy can be bipartisan, the politics cannot. And in that sense, this year shows little sign of ending on Dec. 31. When President Obama moved to sanction Russia over its alleged interference in the U. S. election just concluded, some Republicans who had long called for similar or more severe measures could scarcely bring themselves to approve. House Speaker Paul Ryan called the Obama measures ”appropriate” but also ”overdue” and ”a prime example of this administration’s ineffective foreign policy that has left America weaker in the eyes of the world.” Other GOP leaders sounded much the same theme. ”[We have] been urging President Obama for years to take strong action to deter Russia’s worldwide aggression, including its   operations,” wrote Rep. Devin Nunes,  . chairman of the House Intelligence Committee. ”Now with just a few weeks left in office, the president has suddenly decided that some stronger measures are indeed warranted.” Appearing 

## Preprocessing

In [10]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(max_df=0.9, min_df=2, stop_words='english')  #ignore certain terms when building vocabulary that have very high document freq that show up in 90% of the docs/ words that show min amount of time: it has to show up in at least 2 docs/

In [11]:
dtm = cv.fit_transform(npr['Article'])

In [12]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

## LDA

In [13]:
from sklearn.decomposition import LatentDirichletAllocation

In [14]:
LDA = LatentDirichletAllocation(n_components=7, random_state = 42) # 7 general topics to return

In [15]:
LDA.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=42)

It takes time to update its weights per word per topic. LDA is iterative process.

# Grab the vocabulary of words - Showing Stored Words

In [19]:
len(cv.get_feature_names_out())

54777

In [22]:
type(cv.get_feature_names_out())

numpy.ndarray

In [24]:
cv.get_feature_names_out()[50000]

'transcribe'

In [29]:
import random
random_word_id = random.randint(0, 54777)
cv.get_feature_names_out()[random_word_id]

'brenner'

# Grab the topics - Showing Top Words Per Topic

In [30]:
len(LDA.components_)

7

In [31]:
type(LDA.components_)

numpy.ndarray

In [34]:
LDA.components_.shape

(7, 54777)

In [35]:
LDA.components_

array([[8.64332806e+00, 2.38014333e+03, 1.42900522e-01, ...,
        1.43006821e-01, 1.42902042e-01, 1.42861626e-01],
       [2.76191749e+01, 5.36394437e+02, 1.42857148e-01, ...,
        1.42861973e-01, 1.42857147e-01, 1.42906875e-01],
       [7.22783888e+00, 8.24033986e+02, 1.42857148e-01, ...,
        6.14236247e+00, 2.14061364e+00, 1.42923753e-01],
       ...,
       [3.11488651e+00, 3.50409655e+02, 1.42857147e-01, ...,
        1.42859912e-01, 1.42857146e-01, 1.42866614e-01],
       [4.61486388e+01, 5.14408600e+01, 3.14281373e+00, ...,
        1.43107628e-01, 1.43902481e-01, 2.14271779e+00],
       [4.93991422e-01, 4.18841042e+02, 1.42857151e-01, ...,
        1.42857146e-01, 1.43760101e-01, 1.42866201e-01]])

In [36]:
single_topic = LDA.components_[0]

In [37]:
single_topic.argsort()

array([ 2475, 18302, 35285, ..., 22673, 42561, 42993])

In [39]:
import numpy as np

In [40]:
arr = np.array([10,200,1])

In [41]:
arr

array([ 10, 200,   1])

In [44]:
arr.argsort() # sort from the lowest value to the highest value

array([2, 0, 1])

In [46]:
#ARGSORT returns back --> INDEX POSITIONS SORTED FROM LEAST --> GREATEST
#TOP 10 values (10 GREATEST values)
#last 10 values of ARGSORT()
single_topic.argsort()[-10:] # grab the last 10 values od the result asrsort()// returns the index positions of the 10 highest probability words

array([33390, 36310, 21228, 10425, 31464,  8149, 36283, 22673, 42561,
       42993])

In [49]:
top_20_words = single_topic.argsort()[-20:]

In [50]:
for index in top_20_words:
  print(cv.get_feature_names_out()[index])

president
state
tax
insurance
trump
companies
money
year
federal
000
new
percent
government
company
million
care
people
health
said
says


# Grab the highest probability words per topic

Set up a loop that prints out the top 15 words for each of the 7 topics.

In [51]:
for i, topic in enumerate (LDA.components_):
  print(f"THE TOP 15 WORDS FOR TOPIC #{i}")
  print([cv.get_feature_names_out()[index] for index in topic.argsort()[-15:]])
  print('\n')
  print('\n')

THE TOP 15 WORDS FOR TOPIC #0
['companies', 'money', 'year', 'federal', '000', 'new', 'percent', 'government', 'company', 'million', 'care', 'people', 'health', 'said', 'says']




THE TOP 15 WORDS FOR TOPIC #1
['military', 'house', 'security', 'russia', 'government', 'npr', 'reports', 'says', 'news', 'people', 'told', 'police', 'president', 'trump', 'said']




THE TOP 15 WORDS FOR TOPIC #2
['way', 'world', 'family', 'home', 'day', 'time', 'water', 'city', 'new', 'years', 'food', 'just', 'people', 'like', 'says']




THE TOP 15 WORDS FOR TOPIC #3
['time', 'new', 'don', 'years', 'medical', 'disease', 'patients', 'just', 'children', 'study', 'like', 'women', 'health', 'people', 'says']




THE TOP 15 WORDS FOR TOPIC #4
['voters', 'vote', 'election', 'party', 'new', 'obama', 'court', 'republican', 'campaign', 'people', 'state', 'president', 'clinton', 'said', 'trump']




THE TOP 15 WORDS FOR TOPIC #5
['years', 'going', 've', 'life', 'don', 'new', 'way', 'music', 'really', 'time', 'know'

### Attaching Discovered Topic Labels to Original Articles

In [52]:
dtm

<11992x54777 sparse matrix of type '<class 'numpy.int64'>'
	with 3033388 stored elements in Compressed Sparse Row format>

Create a new column that has topic numner:

In [55]:
topic_results = LDA.transform(dtm)

In [57]:
topic_results.shape

(11992, 7)

In [61]:
topic_results[0].argmax() # returns index position of the highest probability

1

This means that our model thinks that the first article belongs to topic #1.

### Combining with Original Data

In [62]:
npr['Topic'] = topic_results.argmax(axis=1)

In [63]:
npr

Article  Topic
0      In the Washington of 2016, even when the polic...      1
1        Donald Trump has used Twitter  —   his prefe...      1
2        Donald Trump is unabashedly praising Russian...      1
3      Updated at 2:50 p. m. ET, Russian President Vl...      1
4      From photography, illustration and video, to d...      2
...                                                  ...    ...
11987  The number of law enforcement officers shot an...      1
11988    Trump is busy these days with victory tours,...      4
11989  It’s always interesting for the Goats and Soda...      3
11990  The election of Donald Trump was a surprise to...      4
11991  Voters in the English city of Sunderland did s...      0

[11992 rows x 2 columns]